language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g bower
  - npm install -g grunt-cli

script: cd backend && npm install && npm test && cd ../frontend && npm install && bower install && grunt test
